/*
 * MFP project, JFuncParamCfg.java : Designed and developed by Tony Cui in 2021
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JFuncParamCfg.java
 *
 * Created on 26/06/2015, 6:53:58 PM
 */
package jcmdline;

import javax.swing.JPanel;

/**
 *
 * @author tonyc
 */
public class JFuncParamCfg extends JPanel {

    private JApkGenInput mjApkGenInput;

    /**
     * Creates new form JFuncParamCfg
     */
    public JFuncParamCfg(JApkGenInput jApkGenInput) {
        initComponents();
        mjApkGenInput = jApkGenInput;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblParamPrompt = new javax.swing.JLabel();
        txtFieldParamPrompt = new javax.swing.JTextField();
        lblDefaultValue = new javax.swing.JLabel();
        txtFieldDefaultValue = new javax.swing.JTextField();
        chkBoxIsString = new javax.swing.JCheckBox();
        chkBoxNeedsNoInput = new javax.swing.JCheckBox();
        btnDelete = new javax.swing.JButton();

        setName("Form"); // NOI18N

        lblParamPrompt.setText(JCmdLineApp.getStringsClass().get_information_about_parameter());
        lblParamPrompt.setName("lblParamPrompt"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jcmdline.JCmdLineApp.class).getContext().getResourceMap(JFuncParamCfg.class);
        txtFieldParamPrompt.setText(resourceMap.getString("txtFieldParamPrompt.text")); // NOI18N
        txtFieldParamPrompt.setName("txtFieldParamPrompt"); // NOI18N

        lblDefaultValue.setText(JCmdLineApp.getStringsClass().get_parameter_default_value());
        lblDefaultValue.setName("lblDefaultValue"); // NOI18N

        txtFieldDefaultValue.setText(resourceMap.getString("txtFieldDefaultValue.text")); // NOI18N
        txtFieldDefaultValue.setName("txtFieldDefaultValue"); // NOI18N

        chkBoxIsString.setText(JCmdLineApp.getStringsClass().get_param_is_a_string());
        chkBoxIsString.setName("chkBoxIsString"); // NOI18N

        chkBoxNeedsNoInput.setText(JCmdLineApp.getStringsClass().get_param_needs_no_input());
        chkBoxNeedsNoInput.setName("chkBoxNeedsNoInput"); // NOI18N

        btnDelete.setText(JCmdLineApp.getStringsClass().get_delete());
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkBoxIsString)
                        .addGap(18, 18, 18)
                        .addComponent(chkBoxNeedsNoInput))
                    .addComponent(lblParamPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDefaultValue, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFieldDefaultValue))
                    .addComponent(txtFieldParamPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParamPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldParamPrompt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDefaultValue)
                    .addComponent(txtFieldDefaultValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBoxIsString)
                    .addComponent(chkBoxNeedsNoInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        JPanel panelParent = (JPanel) getParent();
        panelParent.remove(this);
        panelParent.revalidate();

        if (mjApkGenInput.getFuncParamCfgCnt() == 0) {
            mjApkGenInput.setUseOptionalParamEnabled(false);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    public boolean isString() {
        return chkBoxIsString.isSelected();
    }

    public boolean needsNoInput() {
        return chkBoxNeedsNoInput.isSelected();
    }

    public String getParamPrompt() {
        return txtFieldParamPrompt.getText();
    }

    public String getDefaultValue() {
        return txtFieldDefaultValue.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JCheckBox chkBoxIsString;
    private javax.swing.JCheckBox chkBoxNeedsNoInput;
    private javax.swing.JLabel lblDefaultValue;
    private javax.swing.JLabel lblParamPrompt;
    private javax.swing.JTextField txtFieldDefaultValue;
    private javax.swing.JTextField txtFieldParamPrompt;
    // End of variables declaration//GEN-END:variables
}
