/*
 * MFP project, JIntegrationInput.java : Designed and developed by Tony Cui in 2021
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JIntegrationInput.java
 *
 * Created on 23/04/2012, 10:20:13 AM
 */
package jcmdline;

/**
 *
 * @author tonyc
 */
public class JIntegrationInput extends javax.swing.JDialog {

    public static final int SELECT_INDEFINITE_INTEGRAL = 0;
    public static final int SELECT_1ST_LEVEL_INTEGRAL = 1;
    public static final int SELECT_2ND_LEVEL_INTEGRAL = 2;
    public static final int SELECT_3RD_LEVEL_INTEGRAL = 3;

    /**
     * Creates new form JIntegrationInput
     */
    public JIntegrationInput(java.awt.Frame parent) {
        super(parent);
        initComponents();
        cboIntegralLevel.removeAllItems();
        cboIntegralLevel.insertItemAt(new Object() {
            @Override
            public String toString() {
                return JCmdLineApp.getStringsClass().get_indefinite_integral();
            }
        }, SELECT_INDEFINITE_INTEGRAL);
        cboIntegralLevel.insertItemAt(new Object() {
            @Override
            public String toString() {
                return JCmdLineApp.getStringsClass().get_single_integral();
            }
        }, SELECT_1ST_LEVEL_INTEGRAL);
        cboIntegralLevel.insertItemAt(new Object() {
            @Override
            public String toString() {
                return JCmdLineApp.getStringsClass().get_double_integral();
            }
        }, SELECT_2ND_LEVEL_INTEGRAL);
        cboIntegralLevel.insertItemAt(new Object() {
            @Override
            public String toString() {
                return JCmdLineApp.getStringsClass().get_triple_integral();
            }
        }, SELECT_3RD_LEVEL_INTEGRAL);
        cboIntegralLevel.setSelectedIndex(SELECT_INDEFINITE_INTEGRAL);
        getRootPane().setDefaultButton(btnCopy2CmdLine);
        panel2ndLevel.setVisible(false);
        panel3rdLevel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIntegralLevel = new javax.swing.JLabel();
        cboIntegralLevel = new javax.swing.JComboBox();
        lblIntegratedExpr = new javax.swing.JLabel();
        txtFieldIntegratedExpr = new javax.swing.JTextField();
        panel1stLevel = new javax.swing.JPanel();
        lbl1stVarName = new javax.swing.JLabel();
        txtField1stVarName = new javax.swing.JTextField();
        lbl1stFrom = new javax.swing.JLabel();
        txtField1stFrom = new javax.swing.JTextField();
        lbl1stTo = new javax.swing.JLabel();
        txtField1stTo = new javax.swing.JTextField();
        lbl1stNumofSteps = new javax.swing.JLabel();
        txtField1stNumofSteps = new javax.swing.JTextField();
        panel2ndLevel = new javax.swing.JPanel();
        lbl2ndVarName = new javax.swing.JLabel();
        txtField2ndVarName = new javax.swing.JTextField();
        lbl2ndFrom = new javax.swing.JLabel();
        txtField2ndFrom = new javax.swing.JTextField();
        lbl2ndTo = new javax.swing.JLabel();
        txtField2ndTo = new javax.swing.JTextField();
        lbl2ndNumofSteps = new javax.swing.JLabel();
        txtField2ndNumofSteps = new javax.swing.JTextField();
        panel3rdLevel = new javax.swing.JPanel();
        lbl3rdVarName = new javax.swing.JLabel();
        txtField3rdVarName = new javax.swing.JTextField();
        lbl3rdFrom = new javax.swing.JLabel();
        txtField3rdFrom = new javax.swing.JTextField();
        lbl3rdTo = new javax.swing.JLabel();
        txtField3rdTo = new javax.swing.JTextField();
        lbl3rdNumofSteps = new javax.swing.JLabel();
        txtField3rdNumofSteps = new javax.swing.JTextField();
        btnCopy2CmdLine = new javax.swing.JButton();

        setTitle(JCmdLineApp.getStringsClass().get_integration_input_title());
        setName("Form"); // NOI18N
        setResizable(false);

        lblIntegralLevel.setText(JCmdLineApp.getStringsClass().get_you_want_to_calculate());
        lblIntegralLevel.setName("lblIntegralLevel"); // NOI18N

        cboIntegralLevel.setName("cboIntegralLevel"); // NOI18N
        cboIntegralLevel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboIntegralLevelItemStateChanged(evt);
            }
        });

        lblIntegratedExpr.setText(JCmdLineApp.getStringsClass().get_single_line_integrated_expr_prompt());
        lblIntegratedExpr.setName("lblIntegratedExpr"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jcmdline.JCmdLineApp.class).getContext().getResourceMap(JIntegrationInput.class);
        txtFieldIntegratedExpr.setText(resourceMap.getString("txtFieldIntegratedExpr.text")); // NOI18N
        txtFieldIntegratedExpr.setName("txtFieldIntegratedExpr"); // NOI18N

        panel1stLevel.setName("panel1stLevel"); // NOI18N

        lbl1stVarName.setText(JCmdLineApp.getStringsClass().get_x_variable_name());
        lbl1stVarName.setName("lbl1stVarName"); // NOI18N

        txtField1stVarName.setText(resourceMap.getString("txtField1stVarName.text")); // NOI18N
        txtField1stVarName.setName("txtField1stVarName"); // NOI18N

        lbl1stFrom.setText(JCmdLineApp.getStringsClass().get_variable_from());
        lbl1stFrom.setName("lbl1stFrom"); // NOI18N

        txtField1stFrom.setText(resourceMap.getString("txtField1stFrom.text")); // NOI18N
        txtField1stFrom.setName("txtField1stFrom"); // NOI18N

        lbl1stTo.setText(JCmdLineApp.getStringsClass().get_variable_to());
        lbl1stTo.setName("lbl1stTo"); // NOI18N

        txtField1stTo.setText(resourceMap.getString("txtField1stTo.text")); // NOI18N
        txtField1stTo.setName("txtField1stTo"); // NOI18N

        lbl1stNumofSteps.setText(JCmdLineApp.getStringsClass().get_variable_number_of_steps());
        lbl1stNumofSteps.setName("lbl1stNumofSteps"); // NOI18N

        txtField1stNumofSteps.setText(resourceMap.getString("txtField1stNumofSteps.text")); // NOI18N
        txtField1stNumofSteps.setName("txtField1stNumofSteps"); // NOI18N

        javax.swing.GroupLayout panel1stLevelLayout = new javax.swing.GroupLayout(panel1stLevel);
        panel1stLevel.setLayout(panel1stLevelLayout);
        panel1stLevelLayout.setHorizontalGroup(
            panel1stLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1stLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1stLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1stLevelLayout.createSequentialGroup()
                        .addComponent(lbl1stFrom)
                        .addGap(18, 18, 18)
                        .addComponent(txtField1stFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl1stTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtField1stTo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl1stNumofSteps)
                        .addGap(10, 10, 10)
                        .addComponent(txtField1stNumofSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1stLevelLayout.createSequentialGroup()
                        .addComponent(lbl1stVarName)
                        .addGap(18, 18, 18)
                        .addComponent(txtField1stVarName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64))
        );
        panel1stLevelLayout.setVerticalGroup(
            panel1stLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1stLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1stLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1stVarName)
                    .addComponent(txtField1stVarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1stLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1stFrom)
                    .addComponent(txtField1stFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1stTo)
                    .addComponent(txtField1stTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl1stNumofSteps)
                    .addComponent(txtField1stNumofSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel2ndLevel.setName("panel2ndLevel"); // NOI18N

        lbl2ndVarName.setText(JCmdLineApp.getStringsClass().get_y_variable_name());
        lbl2ndVarName.setName("lbl2ndVarName"); // NOI18N

        txtField2ndVarName.setText(resourceMap.getString("txtField2ndVarName.text")); // NOI18N
        txtField2ndVarName.setName("txtField2ndVarName"); // NOI18N

        lbl2ndFrom.setText(JCmdLineApp.getStringsClass().get_variable_from());
        lbl2ndFrom.setName("lbl2ndFrom"); // NOI18N

        txtField2ndFrom.setText(resourceMap.getString("txtField2ndFrom.text")); // NOI18N
        txtField2ndFrom.setName("txtField2ndFrom"); // NOI18N

        lbl2ndTo.setText(JCmdLineApp.getStringsClass().get_variable_to());
        lbl2ndTo.setName("lbl2ndTo"); // NOI18N

        txtField2ndTo.setText(resourceMap.getString("txtField2ndTo.text")); // NOI18N
        txtField2ndTo.setName("txtField2ndTo"); // NOI18N

        lbl2ndNumofSteps.setText(JCmdLineApp.getStringsClass().get_variable_number_of_steps());
        lbl2ndNumofSteps.setName("lbl2ndNumofSteps"); // NOI18N

        txtField2ndNumofSteps.setText(resourceMap.getString("txtField2ndNumofSteps.text")); // NOI18N
        txtField2ndNumofSteps.setName("txtField2ndNumofSteps"); // NOI18N

        javax.swing.GroupLayout panel2ndLevelLayout = new javax.swing.GroupLayout(panel2ndLevel);
        panel2ndLevel.setLayout(panel2ndLevelLayout);
        panel2ndLevelLayout.setHorizontalGroup(
            panel2ndLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2ndLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2ndLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2ndLevelLayout.createSequentialGroup()
                        .addComponent(lbl2ndVarName)
                        .addGap(18, 18, 18)
                        .addComponent(txtField2ndVarName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2ndLevelLayout.createSequentialGroup()
                        .addComponent(lbl2ndFrom)
                        .addGap(18, 18, 18)
                        .addComponent(txtField2ndFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl2ndTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtField2ndTo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl2ndNumofSteps)
                        .addGap(10, 10, 10)
                        .addComponent(txtField2ndNumofSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        panel2ndLevelLayout.setVerticalGroup(
            panel2ndLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2ndLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2ndLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2ndVarName)
                    .addComponent(txtField2ndVarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel2ndLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2ndFrom)
                    .addComponent(txtField2ndFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2ndTo)
                    .addComponent(txtField2ndTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl2ndNumofSteps)
                    .addComponent(txtField2ndNumofSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel3rdLevel.setName("panel3rdLevel"); // NOI18N

        lbl3rdVarName.setText(JCmdLineApp.getStringsClass().get_z_variable_name());
        lbl3rdVarName.setName("lbl3rdVarName"); // NOI18N

        txtField3rdVarName.setText(resourceMap.getString("txtField3rdVarName.text")); // NOI18N
        txtField3rdVarName.setName("txtField3rdVarName"); // NOI18N

        lbl3rdFrom.setText(JCmdLineApp.getStringsClass().get_variable_from());
        lbl3rdFrom.setName("lbl3rdFrom"); // NOI18N

        txtField3rdFrom.setText(resourceMap.getString("txtField3rdFrom.text")); // NOI18N
        txtField3rdFrom.setName("txtField3rdFrom"); // NOI18N

        lbl3rdTo.setText(JCmdLineApp.getStringsClass().get_variable_to());
        lbl3rdTo.setName("lbl3rdTo"); // NOI18N

        txtField3rdTo.setText(resourceMap.getString("txtField3rdTo.text")); // NOI18N
        txtField3rdTo.setName("txtField3rdTo"); // NOI18N

        lbl3rdNumofSteps.setText(JCmdLineApp.getStringsClass().get_variable_number_of_steps());
        lbl3rdNumofSteps.setName("lbl3rdNumofSteps"); // NOI18N

        txtField3rdNumofSteps.setText(resourceMap.getString("txtField3rdNumofSteps.text")); // NOI18N
        txtField3rdNumofSteps.setName("txtField3rdNumofSteps"); // NOI18N

        javax.swing.GroupLayout panel3rdLevelLayout = new javax.swing.GroupLayout(panel3rdLevel);
        panel3rdLevel.setLayout(panel3rdLevelLayout);
        panel3rdLevelLayout.setHorizontalGroup(
            panel3rdLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3rdLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3rdLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3rdLevelLayout.createSequentialGroup()
                        .addComponent(lbl3rdFrom)
                        .addGap(18, 18, 18)
                        .addComponent(txtField3rdFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel3rdLevelLayout.createSequentialGroup()
                        .addComponent(lbl3rdVarName)
                        .addGap(18, 18, 18)
                        .addComponent(txtField3rdVarName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(lbl3rdTo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtField3rdTo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl3rdNumofSteps)
                .addGap(10, 10, 10)
                .addComponent(txtField3rdNumofSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        panel3rdLevelLayout.setVerticalGroup(
            panel3rdLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3rdLevelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3rdLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3rdVarName)
                    .addComponent(txtField3rdVarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel3rdLevelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl3rdFrom)
                    .addComponent(txtField3rdFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3rdTo)
                    .addComponent(txtField3rdTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl3rdNumofSteps)
                    .addComponent(txtField3rdNumofSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCopy2CmdLine.setText(JCmdLineApp.getStringsClass().get_copy_to_main_window());
        btnCopy2CmdLine.setName("btnCopy2CmdLine"); // NOI18N
        btnCopy2CmdLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopy2CmdLineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1stLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIntegralLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIntegratedExpr))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboIntegralLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFieldIntegratedExpr, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)))
                    .addComponent(panel2ndLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel3rdLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCopy2CmdLine, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntegralLevel)
                    .addComponent(cboIntegralLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIntegratedExpr)
                    .addComponent(txtFieldIntegratedExpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel1stLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2ndLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3rdLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCopy2CmdLine)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCopy2CmdLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopy2CmdLineActionPerformed

        if (JCmdLineApp.getApplication().isIdle()) {
            // no command is running now so that we can copy.
            String strTmp = "";
            switch (cboIntegralLevel.getSelectedIndex()) {
                case SELECT_1ST_LEVEL_INTEGRAL:
                    strTmp = "Integrate(\"" + txtFieldIntegratedExpr.getText() + "\", \"" + txtField1stVarName.getText() + "\", "
                            + txtField1stFrom.getText() + ", " + txtField1stTo.getText() + ", " + txtField1stNumofSteps.getText() + ")";
                    break;
                case SELECT_2ND_LEVEL_INTEGRAL:
                    strTmp = "Integrate(\\\"" + txtFieldIntegratedExpr.getText() + "\\\", \\\"" + txtField1stVarName.getText() + "\\\", "
                            + txtField1stFrom.getText() + ", " + txtField1stTo.getText() + ", " + txtField1stNumofSteps.getText() + ")";
                    strTmp = "Integrate(\"" + strTmp + "\", \"" + txtField2ndVarName.getText() + "\", "
                            + txtField2ndFrom.getText() + ", " + txtField2ndTo.getText() + ", " + txtField2ndNumofSteps.getText() + ")";
                    break;
                case SELECT_3RD_LEVEL_INTEGRAL:
                    strTmp = "Integrate(\\\\\\\"" + txtFieldIntegratedExpr.getText() + "\\\\\\\", \\\\\\\"" + txtField1stVarName.getText() + "\\\\\\\", "
                            + txtField1stFrom.getText() + ", " + txtField1stTo.getText() + ", " + txtField1stNumofSteps.getText() + ")";
                    strTmp = "Integrate(\\\"" + strTmp + "\\\", \\\"" + txtField2ndVarName.getText() + "\\\", "
                            + txtField2ndFrom.getText() + ", " + txtField2ndTo.getText() + ", " + txtField2ndNumofSteps.getText() + ")";
                    strTmp = "Integrate(\"" + strTmp + "\", \"" + txtField3rdVarName.getText() + "\", "
                            + txtField3rdFrom.getText() + ", " + txtField3rdTo.getText() + ", " + txtField3rdNumofSteps.getText() + ")";
                    break;
                default:    //SELECT_INDEFINITE_INTEGRAL
                    strTmp = "Integrate(\"" + txtFieldIntegratedExpr.getText() + "\", \"" + txtField1stVarName.getText() + "\")";
                    break;
            }
            JCmdLineView cmdLineView = (JCmdLineView) JCmdLineApp.getApplication().getMainView();
            cmdLineView.pasteNewCmd(strTmp);
        }
    }//GEN-LAST:event_btnCopy2CmdLineActionPerformed

    private void cboIntegralLevelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboIntegralLevelItemStateChanged
        boolean bDefInteg = true;
        if (cboIntegralLevel.getSelectedIndex() == SELECT_1ST_LEVEL_INTEGRAL) {
            panel1stLevel.setVisible(true);
            panel2ndLevel.setVisible(false);
            panel3rdLevel.setVisible(false);
        } else if (cboIntegralLevel.getSelectedIndex() == SELECT_2ND_LEVEL_INTEGRAL) {
            panel1stLevel.setVisible(true);
            panel2ndLevel.setVisible(true);
            panel3rdLevel.setVisible(false);
        } else if (cboIntegralLevel.getSelectedIndex() == SELECT_3RD_LEVEL_INTEGRAL) {
            panel1stLevel.setVisible(true);
            panel2ndLevel.setVisible(true);
            panel3rdLevel.setVisible(true);
        } else {    //SELECT_INDEFINITE_INTEGRAL
            panel1stLevel.setVisible(true);
            panel2ndLevel.setVisible(false);
            panel3rdLevel.setVisible(false);
            bDefInteg = false;
        }
        lbl1stFrom.setVisible(bDefInteg);
        lbl1stTo.setVisible(bDefInteg);
        lbl1stNumofSteps.setVisible(bDefInteg);
        txtField1stFrom.setVisible(bDefInteg);
        txtField1stTo.setVisible(bDefInteg);
        txtField1stNumofSteps.setVisible(bDefInteg);

        this.pack();
    }//GEN-LAST:event_cboIntegralLevelItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy2CmdLine;
    private javax.swing.JComboBox cboIntegralLevel;
    private javax.swing.JLabel lbl1stFrom;
    private javax.swing.JLabel lbl1stNumofSteps;
    private javax.swing.JLabel lbl1stTo;
    private javax.swing.JLabel lbl1stVarName;
    private javax.swing.JLabel lbl2ndFrom;
    private javax.swing.JLabel lbl2ndNumofSteps;
    private javax.swing.JLabel lbl2ndTo;
    private javax.swing.JLabel lbl2ndVarName;
    private javax.swing.JLabel lbl3rdFrom;
    private javax.swing.JLabel lbl3rdNumofSteps;
    private javax.swing.JLabel lbl3rdTo;
    private javax.swing.JLabel lbl3rdVarName;
    private javax.swing.JLabel lblIntegralLevel;
    private javax.swing.JLabel lblIntegratedExpr;
    private javax.swing.JPanel panel1stLevel;
    private javax.swing.JPanel panel2ndLevel;
    private javax.swing.JPanel panel3rdLevel;
    private javax.swing.JTextField txtField1stFrom;
    private javax.swing.JTextField txtField1stNumofSteps;
    private javax.swing.JTextField txtField1stTo;
    private javax.swing.JTextField txtField1stVarName;
    private javax.swing.JTextField txtField2ndFrom;
    private javax.swing.JTextField txtField2ndNumofSteps;
    private javax.swing.JTextField txtField2ndTo;
    private javax.swing.JTextField txtField2ndVarName;
    private javax.swing.JTextField txtField3rdFrom;
    private javax.swing.JTextField txtField3rdNumofSteps;
    private javax.swing.JTextField txtField3rdTo;
    private javax.swing.JTextField txtField3rdVarName;
    private javax.swing.JTextField txtFieldIntegratedExpr;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getCopy2CmdLineBtn() {
        return btnCopy2CmdLine;
    }
}
