/*
 * MFP project, JMultiXYCurveDef.java : Designed and developed by Tony Cui in 2021
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * JMultiXYCurveDef.java
 *
 * Created on 24/04/2012, 10:03:02 AM
 */
package jcmdline;

/**
 *
 * @author tonyc
 */
public class JMultiXYCurveDef extends javax.swing.JPanel {

    private class PntStyleItem extends Object {

        public PntStyleItem(String strNameSeenBySys, String strNameSeenByUser) {
            mstrPntStyleNameSeenBySys = strNameSeenBySys;
            mstrPntStyleNameSeenByUser = strNameSeenByUser;
        }
        public String mstrPntStyleNameSeenBySys = "point";
        public String mstrPntStyleNameSeenByUser = JCmdLineApp.getStringsClass().get_point_point_style();

        @Override
        public String toString() {
            return mstrPntStyleNameSeenByUser;
        }
    }

    private class ColorItem extends Object {

        public ColorItem(String strNameSeenBySys, String strNameSeenByUser) {
            mstrColorNameSeenBySys = strNameSeenBySys;
            mstrColorNameSeenByUser = strNameSeenByUser;
        }
        public String mstrColorNameSeenBySys = "white";
        public String mstrColorNameSeenByUser = JCmdLineApp.getStringsClass().get_white_color();

        @Override
        public String toString() {
            return mstrColorNameSeenByUser;
        }
    }

    /**
     * Creates new form JMultiXYCurveDef
     */
    public JMultiXYCurveDef(JMultiXYChartDef chartDef) {
        initComponents();
        mChartDefParent = chartDef;
        cboCurvePntStyle.removeAllItems();
        cboCurvePntStyle.addItem(new PntStyleItem("point", JCmdLineApp.getStringsClass().get_point_point_style()));
        cboCurvePntStyle.addItem(new PntStyleItem("circle", JCmdLineApp.getStringsClass().get_circle_point_style()));
        cboCurvePntStyle.addItem(new PntStyleItem("triangle", JCmdLineApp.getStringsClass().get_triangle_point_style()));
        cboCurvePntStyle.addItem(new PntStyleItem("square", JCmdLineApp.getStringsClass().get_square_point_style()));
        cboCurvePntStyle.addItem(new PntStyleItem("diamond", JCmdLineApp.getStringsClass().get_diamond_point_style()));
        cboCurvePntStyle.addItem(new PntStyleItem("x", JCmdLineApp.getStringsClass().get_x_point_style()));
        cboCurveColor.removeAllItems();
        cboCurveColor.addItem(new ColorItem("white", JCmdLineApp.getStringsClass().get_white_color()));
        cboCurveColor.addItem(new ColorItem("black", JCmdLineApp.getStringsClass().get_black_color()));
        cboCurveColor.addItem(new ColorItem("blue", JCmdLineApp.getStringsClass().get_blue_color()));
        cboCurveColor.addItem(new ColorItem("cyan", JCmdLineApp.getStringsClass().get_cyan_color()));
        cboCurveColor.addItem(new ColorItem("dkgray", JCmdLineApp.getStringsClass().get_dkgray_color()));
        cboCurveColor.addItem(new ColorItem("gray", JCmdLineApp.getStringsClass().get_gray_color()));
        cboCurveColor.addItem(new ColorItem("green", JCmdLineApp.getStringsClass().get_green_color()));
        cboCurveColor.addItem(new ColorItem("ltgray", JCmdLineApp.getStringsClass().get_ltgray_color()));
        cboCurveColor.addItem(new ColorItem("magenta", JCmdLineApp.getStringsClass().get_magenta_color()));
        cboCurveColor.addItem(new ColorItem("red", JCmdLineApp.getStringsClass().get_red_color()));
        cboCurveColor.addItem(new ColorItem("yellow", JCmdLineApp.getStringsClass().get_yellow_color()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurveTitle = new javax.swing.JLabel();
        txtFieldCurveTitle = new javax.swing.JTextField();
        lblCurveColor = new javax.swing.JLabel();
        cboCurveColor = new javax.swing.JComboBox();
        lblTFrom = new javax.swing.JLabel();
        txtFieldTFrom = new javax.swing.JTextField();
        lblTTo = new javax.swing.JLabel();
        txtFieldTTo = new javax.swing.JTextField();
        lblTStep = new javax.swing.JLabel();
        txtFieldTStep = new javax.swing.JTextField();
        lblXt = new javax.swing.JLabel();
        txtFieldXt = new javax.swing.JTextField();
        lblYt = new javax.swing.JLabel();
        txtFieldYt = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblPntStylePrompt = new javax.swing.JLabel();
        cboCurvePntStyle = new javax.swing.JComboBox();
        chkboxCurveShowLn = new javax.swing.JCheckBox();
        lblXEqual = new javax.swing.JLabel();
        lblYEqual = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        lblCurveTitle.setText(JCmdLineApp.getStringsClass().get_curve_title_prompt());
        lblCurveTitle.setName("lblCurveTitle"); // NOI18N

        txtFieldCurveTitle.setName("txtFieldCurveTitle"); // NOI18N

        lblCurveColor.setText(JCmdLineApp.getStringsClass().get_curve_color_prompt());
        lblCurveColor.setName("lblCurveColor"); // NOI18N

        cboCurveColor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCurveColor.setName("cboCurveColor"); // NOI18N

        lblTFrom.setText(JCmdLineApp.getStringsClass().get_t_from_prompt());
        lblTFrom.setName("lblTFrom"); // NOI18N

        txtFieldTFrom.setName("txtFieldTFrom"); // NOI18N

        lblTTo.setText(JCmdLineApp.getStringsClass().get_t_to_prompt());
        lblTTo.setName("lblTTo"); // NOI18N

        txtFieldTTo.setName("txtFieldTTo"); // NOI18N

        lblTStep.setText(JCmdLineApp.getStringsClass().get_t_step_prompt());
        lblTStep.setName("lblTStep"); // NOI18N

        txtFieldTStep.setName("txtFieldTStep"); // NOI18N

        lblXt.setName("lblXt"); // NOI18N

        txtFieldXt.setName("txtFieldXt"); // NOI18N

        lblYt.setName("lblYt"); // NOI18N

        txtFieldYt.setName("txtFieldYt"); // NOI18N

        btnDelete.setText(JCmdLineApp.getStringsClass().get_delete_curve_btn_text());
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText(JCmdLineApp.getStringsClass().get_clear_curve_btn_text());
        btnClear.setName("btnClear"); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jSeparator1.setName("jSeparator1"); // NOI18N

        lblPntStylePrompt.setText(JCmdLineApp.getStringsClass().get_curve_point_style_prompt());
        lblPntStylePrompt.setName("lblPntStylePrompt"); // NOI18N

        cboCurvePntStyle.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCurvePntStyle.setName("cboCurvePntStyle"); // NOI18N

        chkboxCurveShowLn.setSelected(true);
        chkboxCurveShowLn.setText(JCmdLineApp.getStringsClass().get_curve_show_line_chkbox_prompt());
        chkboxCurveShowLn.setName("chkboxCurveShowLn"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jcmdline.JCmdLineApp.class).getContext().getResourceMap(JMultiXYCurveDef.class);
        lblXEqual.setText(resourceMap.getString("lblXEqual.text")); // NOI18N
        lblXEqual.setName("lblXEqual"); // NOI18N

        lblYEqual.setText(resourceMap.getString("lblYEqual.text")); // NOI18N
        lblYEqual.setName("lblYEqual"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurveTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFieldCurveTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCurveColor)
                .addGap(18, 18, 18)
                .addComponent(cboCurveColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear))
                    .addComponent(lblXt)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblXEqual)
                                .addGap(10, 10, 10)
                                .addComponent(txtFieldXt, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTFrom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldTFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTTo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFieldTTo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblYEqual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFieldYt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTStep)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                .addComponent(lblYt)
                                .addGap(74, 74, 74))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFieldTStep, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPntStylePrompt, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboCurvePntStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(chkboxCurveShowLn, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                        .addGap(131, 131, 131)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurveTitle)
                    .addComponent(txtFieldCurveTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurveColor)
                    .addComponent(cboCurveColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPntStylePrompt)
                    .addComponent(cboCurvePntStyle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkboxCurveShowLn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTFrom)
                    .addComponent(txtFieldTFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTTo)
                    .addComponent(txtFieldTTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTStep)
                    .addComponent(txtFieldTStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXt)
                    .addComponent(txtFieldXt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYt)
                    .addComponent(lblXEqual)
                    .addComponent(lblYEqual)
                    .addComponent(txtFieldYt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnClear))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (mChartDefParent != null) {
            mChartDefParent.deleteCurve(mnIndex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cboCurvePntStyle.setSelectedIndex(0);
        chkboxCurveShowLn.setSelected(true);
        cboCurveColor.setSelectedIndex(0);
        txtFieldCurveTitle.setText("");
        txtFieldTFrom.setText("");
        txtFieldTStep.setText("");
        txtFieldTTo.setText("");
        txtFieldXt.setText("");
        txtFieldYt.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox cboCurveColor;
    private javax.swing.JComboBox cboCurvePntStyle;
    private javax.swing.JCheckBox chkboxCurveShowLn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCurveColor;
    private javax.swing.JLabel lblCurveTitle;
    private javax.swing.JLabel lblPntStylePrompt;
    private javax.swing.JLabel lblTFrom;
    private javax.swing.JLabel lblTStep;
    private javax.swing.JLabel lblTTo;
    protected javax.swing.JLabel lblXEqual;
    private javax.swing.JLabel lblXt;
    protected javax.swing.JLabel lblYEqual;
    private javax.swing.JLabel lblYt;
    private javax.swing.JTextField txtFieldCurveTitle;
    private javax.swing.JTextField txtFieldTFrom;
    private javax.swing.JTextField txtFieldTStep;
    private javax.swing.JTextField txtFieldTTo;
    private javax.swing.JTextField txtFieldXt;
    private javax.swing.JTextField txtFieldYt;
    // End of variables declaration//GEN-END:variables

    public String getCurveTitle() {
        return txtFieldCurveTitle.getText();
    }

    public String getCurvePntStyle() {
        return ((PntStyleItem) (cboCurvePntStyle.getSelectedItem())).mstrPntStyleNameSeenBySys;
    }

    public boolean getCurveShowLn() {
        return chkboxCurveShowLn.isSelected();
    }

    public String getCurveColor() {
        return ((ColorItem) (cboCurveColor.getSelectedItem())).mstrColorNameSeenBySys;
    }

    public String getTFrom() {
        return txtFieldTFrom.getText();
    }

    public String getTTo() {
        return txtFieldTTo.getText();
    }

    public String getTStep() {
        return txtFieldTStep.getText();
    }

    public String getXt() {
        return txtFieldXt.getText();
    }

    public String getYt() {
        return txtFieldYt.getText();
    }

    public int mnIndex = 0;

    private JMultiXYChartDef mChartDefParent = null;
}
